export  {Search, Check, Menu} from '@styled-icons/boxicons-regular' 
export  {PersonAdd} from '@styled-icons/ionicons-sharp'
export  {Bell, User} from '@styled-icons/boxicons-solid'
export  {Fire} from '@styled-icons/heroicons-solid'
export {Database} from '@styled-icons/foundation'
export {LiveHelp, History} from '@styled-icons/material'
export {Cycle, LocationPin} from '@styled-icons/entypo'
export {CloseCircle, Rocket} from '@styled-icons/ionicons-outline'
export {Rocket2} from '@styled-icons/remix-fill'
export {UserAstronaut} from '@styled-icons/fa-solid'
export {Run} from '@styled-icons/fluentui-system-regular'